# Version of docker-compose
version: '3'

services:
  phoenix:
    build:
      context: ./hello
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: postgres
      PGPORT: 5432
      # PGHOST refers to the service postgres that we have defined in this docker-compose file
      PGHOST: postgres
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  # Use the pre-defined PostgreSQL image
  # NOTE: We have to connect to the default database and get that running FIRST before use mix ecto.create
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:

