# Version of docker-compose
version: '3'

services:
  phoenix-dev:
    build:
      context: ./hello
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: hello_dev
      PGPORT: 5432
      # PGHOST refers to the service postgres that we have defined in this docker-compose file
      PGHOST: postgres
    ports:
      - "4000:4000"
    volumes:
      # Explicitly map our Phoenix app folder to the path on our Docker container for static hot reloading to work
      - ./hello:/app
    depends_on:
      - postgres

  # Use the pre-defined PostgreSQL image
  # NOTE: We have to connect to the default database and get that running FIRST before use mix ecto.create
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: always
    # volumes:
    #   # Use for an ephemeral PostgreSQL database; make sure you uncomment volumes below
    #   - pgdata:/var/lib/postgresql/data

      # # Use to persist data in PostgreSQL database; make sure you comment out volumes below
      # - ./hello/_postgresql/data:/var/lib/postgresql/data

# volumes:
#   pgdata:
